name: Check Resources

on: [push,pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Run checks
        id: checks
        # shell: bash +e +o pipefail {0}
        # continue-on-error: true
        run: |
          gem install awesome_bot
          awesome_bot --allow-redirect --allow-ssl --allow 502 --allow-timeout README.md
